### ISSUE TITLE
Cache issues 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/spec-prod#105]
Running:
https://github.com/w3c/secure-payment-confirmation/runs/3648782752

It complains:
![Screen Shot 2021-09-20 at 4 46 45 pm](https://user-images.githubusercontent.com/870154/133964989-f235b7ea-1cf3-485b-a151-ccc673fd879d.png)

Any way to force it to clear the cache?

**Comment by marcoscaceres** [comment]
Also came up here:
https://github.com/w3c/webappsec-secure-contexts/commit/3d8830aa2d440278e5903a237482335b1f71273a

**Comment by marcoscaceres** [comment]
Potential fix or workaround
https://github.com/w3c/webappsec-secure-contexts/pull/96/files

Adding `.cache` to .gitignore.

**Comment by saschanaz** [comment]
Yeah but it's quite surprising.

>Any way to force it to clear the cache?

Just `rm -rf .cache`?

**Comment by marcoscaceres** [comment]
@sidvishnoi is looking at it now. He will let us now what's best.

**Comment by sidvishnoi** [comment]
Found the source of `.cache`:
https://github.com/w3c/spec-prod/blob/a872d584bb25152e66e418fd947c86c8799c6291/src/validate-webidl.ts#L20-L23

Sending PR...

**Comment by sidvishnoi** [comment]
Fixed and released in v2 ≡ v2.6.1

If your repository has the stray `.cache` dir in your GitHub pages branch, please remove it manually once. It won't be added in next publishes.
