### ISSUE TITLE
Add option to deploy additional resources loaded via css or favicon

### ISSUE THREAD

**Issue by himorin** [w3c/spec-prod#109]
from https://github.com/immersive-web/webxr/issues/1227

Immersive-Web WG specs are loading additional images (shown next to W3C logo) and favicons, which are specified via css (e.g. `content: url(images/spec-logo.png);`) or `<link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">`. It seems these are not supported by `subresources` TS module, and resulted in not listed in `Finding relevant assets`. 

example: https://github.com/immersive-web/webxr/runs/3722938737?check_suite_focus=true

This results into error by link checker since required resources (images and favicons) are not included into archived package. 
We could include these resource as BASE64 encoded values (really??), but we'd request this as new feature. Sorry if there is already an option to do this, and please kindly point me if exists.

**Comment by sidvishnoi** [comment]
These two are indeed not supported as of now. The subresources module does [fetch background images from CSS](https://github.com/sidvishnoi/subresources/blob/b1e616a9b523ed8762f00881a2da427a8e7a65ad/index.ts#L155-L184), but not from `content: url()`. For favicons, [it should be straight-forward](https://github.com/sidvishnoi/subresources/blob/b1e616a9b523ed8762f00881a2da427a8e7a65ad/index.ts#L234-L241). I'll try to find some time this week, unless someone sends a PR first.

**Comment by sidvishnoi** [comment]
Heh. I decided to spend some time on this.
- Released [subresources v1.2.0](https://github.com/sidvishnoi/subresources/releases/tag/v1.2.0) with above features,
- integrated in spec-prod with https://github.com/w3c/spec-prod/commit/0f52c655ce83406cdaf173d82f68d01af7e1b2a9, and
- released spec-prod `v2 ≡ v2.6.2`.

Please re-run the workflow and let me how it goes.

**Comment by himorin** [comment]
sorry for late catch. it's working now
https://www.w3.org/TR/2021/WD-webxr-20210930/
