### ISSUE TITLE
Support username-password in Echidna publish

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/spec-prod#11]

**Comment by dontcallmedom** [comment]
I think username/password is a broken pattern for Echidna - I would not want to record them as github secrets in any of my repositories, and I don't think we should encourage anyone to do so.

https://github.com/w3c/echidna/issues/492 is the request where this is being discussed, with a specific proposal

**Comment by sidvishnoi** [comment]
Closing as we would go the token way instead.
