### ISSUE TITLE
Validation checks source, not output

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/spec-prod#115]
The [documentation on validation](https://w3c.github.io/spec-prod/#run-as-a-validator-on-pull-requests) says spec-prod builds the doc, then validates the result. However, in some [test runs with validation included](https://github.com/w3c/core-aam/runs/4226822255?check_suite_focus=true) we see on line 400 that the file that is built to index.html.built.html, but on line 542 it validates index.html, the original source. The validation therefore fails since there are custom features in the source that are transformed to valid HTML during the build.

Either the tool should work as documented, or if the intent is to validate the source, update the documentation. I don't know which was the intended design choice.

**Comment by sidvishnoi** [comment]
It's still validating the built file, just it has been renamed to `index.html` [^1]

Relevant code: https://github.com/w3c/spec-prod/blob/952786e0cf6d30139e585e05701ce7997758795b/src/build.ts#L143

> The validation therefore fails since there are custom features in the source that are transformed to valid HTML during the build.

Looking at [live/processed ReSpec document](https://rawcdn.githack.com/w3c/core-aam/62a1a7e12b55e9e28a5838c34256bb8bc9f0ed27/index.html), it appears the custom ReSpec plugins aren't removing the `<pref>` element at [index.html#L293](https://github.com/w3c/core-aam/blob/62a1a7e12b55e9e28a5838c34256bb8bc9f0ed27/index.html#L293), causing the HTML validation error.

NB: The built output can be accessed at https://github.com/w3c/core-aam/actions/runs/1467562510 (download the "spec-prod-result" in the Artifacts section).


[^1]: https://github.com/w3c/core-aam/runs/4226822255?check_suite_focus=true#step:3:422
