### ISSUE TITLE
w3c-publish: upload tar instead of using manifest

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/spec-prod#12]
- does not rely on spec-generator. as we already have built the spec, so don't need to build it again.
- user's don't need to create a manifest
- bikeshed uses tar upload instead of manifest

Will need to support https://github.com/sidvishnoi/spec-prod/issues/11 for this.

Might stop supporting manifest based deployment altogether when this comes (breaking change, v2)

**Comment by dontcallmedom** [comment]
https://github.com/w3c/echidna/issues/492#issuecomment-770834924 means it should now be possible to authenticate bikeshed uploads from a github action!

**Comment by dontcallmedom** [comment]
see also https://lists.w3.org/Archives/Public/spec-prod/2021JanMar/0016.html for imminent bikeshed support (https://github.com/tabatkins/bikeshed/issues/1102)
