### ISSUE TITLE
Force "prepare for TR" metadata setting for Bikeshed specs

### ISSUE THREAD

**Issue by tidoust** [w3c/spec-prod#128]
Initially raised against Bikeshed in https://github.com/tabatkins/bikeshed/issues/2242.

Bikeshed does not run a series of "fixups" to comply with PubRules by default. These need to be enabled through the [Prepare for TR](https://tabatkins.github.io/bikeshed/#metadata-prepare-for-tr) metadata setting. The action should take care of that automatically.

This has not been caught before because the PubRules checker remained somewhat lax on some of the rules. It now (starting March 3rd) enforces the order of stylesheets in particular, and automated publications of Bikeshed specs to TR no longer work as a result.

Although that setting is only needed to publish specs to TR, I would argue that the setting should be set for the generation of the Editor's Draft as well, so that the Editor's Draft and the TR version remain as close as possible.

**Comment by sidvishnoi** [comment]
For now, I think we should enable it for TR only to avoid breaking ED/gh-pages spec workflows.

**Comment by tidoust** [comment]
> For now, I think we should enable it for TR only to avoid breaking ED/gh-pages spec workflows.

That's good for now. What I'm worried about is that editors and group participants probably look at the Editor's Draft most of the times, meaning that there will be fewer eyes on the TR version, and so fewer eyes to spot styling issues that could potentially arise when the order of stylesheets gets changed. I wouldn't expect that to be a common problem though.
