### ISSUE TITLE
Error with template make error message confusing

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/spec-prod#130]
when the spec-prod build fails (e.g. due to a bikeshed generation error), the `OUTPUTS_BUILD` parts of `action.yml` fail in cascade, which buries the actual generation error under the list of error executing action.yml, see for instance https://github.com/w3c/webtransport/runs/5745333039?check_suite_focus=true and https://github.com/w3c/webtransport/pull/395#issuecomment-1082707774 for the confusion it generates

**Comment by sidvishnoi** [comment]
Duplicate of #117
