### ISSUE TITLE
TR: Deploy additional files

### ISSUE THREAD

**Issue by tidoust** [w3c/spec-prod#131]
Issue #39 covers deploying additional files to GitHub Pages.

The Media Source Extensions spec uses a [static HTML document](https://w3c.github.io/media-source/pipeline_model_description.html) to describe the pipeline featured in the [introduction](https://w3c.github.io/media-source/#introduction).

This static HTML document also needs to be deployed with the spec. Deploying to GitHub Pages is easy as suggested in #39 comments. However, there is no easy way to deploy that static HTML document automatically to /TR, along with the spec. It would need to be included in the request to Echidna with the other assets, but spec-prod does not provide any hook for that.

I wonder whether there could be an option to list additional static files that also need to be deployed to /TR.

Alternatively, spec-prod could perhaps figure things out all by itself, similarly to how it detects images, stylesheets, etc. that need to be included.

Typically, the spec currently uses the following markup to link to this document:

```html
<a href="pipeline_model_description.html#pipelinedesc">
  <picture><img src="pipeline_model.svg" alt="Media Source Pipeline Model Diagram"></picture>
</a>
```

This automated approach would be great but requires some recursion (the static HTML file could itself link to additional resources).

**Comment by sidvishnoi** [comment]
I'll try to find some this weekend for this and #39, with manual file lists/globs. The automated one might cover both cases though, as it's unlikely we'll upload a file that isn't referenced from the spec somehow. I'll think about it on weekend, feedback welcome.

**Comment by xfq** [comment]
The [MiniApp Standardization White Paper](https://w3c.github.io/miniapp/white-paper/) also links to a [static HTML document](https://w3c.github.io/miniapp/white-paper/comparison.html). It would be useful to include this automatically or manually in the configuration file.
