### ISSUE TITLE
The specified node version file at `.nvmrc` does not exist

### ISSUE THREAD

**Issue by tidoust** [w3c/spec-prod#164]
Latest version of spec-prod seems to create failures, see https://github.com/w3c/mediasession/actions/runs/6157270766 for instance.

The error message is "The specified node version file at: /home/runner/work/mediasession/mediasession/.nvmrc does not exist". I wonder whether the spec-prod code now looks for an `.nvmrc` file, which ends up being looked for in the root folder of the repository that runs spec-prod (and not in the root folder of spec-prod itself).

Or is it because switch to v4 is not only recommended but actually mandatory for `actions/checkout@v2`?

**Comment by sidvishnoi** [comment]
I didn't see these issues during CI maybe because I tested within this repository. It seems I need to provide full path to `.nvmrc` so it looks it within spec-prod and not in repository root. Will create a fork and test it.

Thanks for reporting!
