### ISSUE TITLE
Spec-prod failing

### ISSUE THREAD

**Issue by qingxinwu** [w3c/spec-prod#175]
We noticed that today our builds ([example failded build](https://github.com/WICG/turtledove/pull/1124/checks)) started failing with the following error from spec-prod:

```
Validating Web IDL defined in index.html.
pnpm add reffy@15
  reffy 15.0.2
  Could not find Chrome (ver. 123.0.6312.105). This can occur if either
    1. you did not perform an installation before running the script (e.g. npx puppeteer browsers install chrome) or
    2. your cache path is incorrectly configured (which is: /home/runner/.cache/puppeteer).
  For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
```

Is it a bug introduced by recent changes to spec-prod, like https://github.com/w3c/spec-prod/pull/155? There were a few other PRs merged yesterday as well.

**Comment by marcoscaceres** [comment]
Seeing the same for Web Manifest.

**Comment by tidoust** [comment]
Same as #176, see discussion over there.
