### ISSUE TITLE
spec-prod@v2 fails with reffy@15, worked with reffy@4.0.5

### ISSUE THREAD

**Issue by himorin** [w3c/spec-prod#176]
after https://github.com/w3c/spec-prod/commit/c6d5322021bcd22d44885116044cf27a0a534b03 by @dontcallmedom  merged, spec-prod fails with following error.

```
Validate Web IDL
  Validating Web IDL defined in index.html...
  $ pnpm add reffy@15
  + reffy 15.0.2
  Could not find Chrome (ver. 123.0.6312.105). This can occur if either
   1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
   2. your cache path is incorrectly configured (which is: /home/runner/.cache/puppeteer).
  For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
```

**Comment by dontcallmedom** [comment]
cc @tidoust

**Comment by himorin** [comment]
it seems we have PUPPETEER_SKIP_DOWNLOAD flag on, and this forces to skip downloading Chromium. Not sure why it was working with reffy@4.0.5...
https://github.com/w3c/spec-prod/blob/c6d5322021bcd22d44885116044cf27a0a534b03/action.yml#L78

**Comment by tidoust** [comment]
That is most likely the problem, but I don't understand why ;)

The action does not download Puppeteer but sets the `PUPPETEER_EXECUTABLE_PATH` env variable to the local Chrome, which should give Puppeteer what it needs (the action also uses Puppeteer outside of Reffy)

https://github.com/w3c/spec-prod/blob/c6d5322021bcd22d44885116044cf27a0a534b03/src/build.ts#L181-L182

https://github.com/w3c/spec-prod/blob/c6d5322021bcd22d44885116044cf27a0a534b03/src/constants.ts#L11-L12

Reffy merely calls `puppeteer.launch({ headless: true })`, which should be enough to make Puppeteer use the environment variable according to [Puppeteer documentation](https://pptr.dev/api/puppeteer.configuration).

@sidvishnoi, I can update Reffy to pass an `executablePath` parameter to the call to `Puppeteer.launch` set to `process.env['PUPPETEER_EXECUTABLE_PATH']`, but I'm not sure that would change anything?

**Comment by tidoust** [comment]
Oh wait, the answer is right in the lines I copied, I just misread them!
The code does not set an environment variable, it creates a `PUPPETEER_ENV` variable from the environment variable!

**Comment by sidvishnoi** [comment]
I'll set the env var in spec-prod instead. That's what we do with respec build too.

**Comment by sidvishnoi** [comment]
Just started my day. Expect fix with test in 15min.
