### ISSUE TITLE
“Could not find Chrome”—Broken by latest spec-prod update?

### ISSUE THREAD

**Issue by frivoal** [w3c/spec-prod#185]
Things used to work, but now they don't:

Compare:
* OK: https://github.com/w3c/html-ruby/actions/runs/9277810751/job/25527688988
* Fail: https://github.com/w3c/html-ruby/actions/runs/9284364647/job/25546591007

There was no change on my side. I suspect the culprit is https://github.com/w3c/spec-prod/commit/60b3790b5f8a1606d2f0d99c157e83b444c80416

**Comment by frivoal** [comment]
Or maybe it's something else? Seems similar to https://github.com/w3c/spec-prod/issues/179

**Comment by sidvishnoi** [comment]
I think I should stop using `PUPPETEER_EXECUTABLE_PATH` env var altogether (We try to existing google-chrome executable where possible). It'll cause a performance hit, but at least it won't break. Will investigate further..

**Comment by frivoal** [comment]
Thanks, that worked.
