### ISSUE TITLE
Deploy minimal files to GitHub pages

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/spec-prod#2]
Do not commit files that don't make sense to be on gh-pages branch, e.g. `.github/*`, `package.json`, `.editorconfig`.
But make sure all specifications assets (CSS, JS, images, fonts etc.) are committed.

**Comment by dontcallmedom** [comment]
interesting intersection with #13 in terms of identifying relevant files (which the Echidna manifest also achieves to do to upload all the necessary files)

**Comment by sidvishnoi** [comment]
Yes. I'm hoping to not require Echidna manifest to support uploading a tar (https://github.com/sidvishnoi/spec-prod/issues/12). So, two potatoes with one fork (something like that).

**Comment by sidvishnoi** [comment]
Closed via 97dab6a149a3add41fc2a9427fcf690a278033d6
