### ISSUE TITLE
Support Pubrules validator

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/spec-prod#3]
Integrate https://github.com/w3c/specberus/ somehow. Preferably, work on a CLI and Node API with the specberus team.

**Comment by dontcallmedom** [comment]
wouldn't [echidna dry-run](https://github.com/w3c/echidna/wiki/How-to-use-Echidna#rehearse-publication-dry-run) achieve what's needed here?

**Comment by sidvishnoi** [comment]
It will, but that's still an additional job for Echidna (on every PR commit) which can be done locally in GitHub action (like markup and link validators are done).

**Comment by dontcallmedom** [comment]
makes sense, thx

**Comment by marcoscaceres** [comment]
Just noting that this is still experimental... but mostly works :)
