### ISSUE TITLE
gh-pages: deploy additional files

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/spec-prod#39]
From Francois: Add an option to deploy additional files like explainers to GH pages.

**Comment by xfq** [comment]
In some repos, there are other vanilla HTML files in addition to the specs, such as https://github.com/w3c/clreq/blob/gh-pages/charter/index.html in [clreq](https://github.com/w3c/clreq).

Does spec-prod support deploy those vanilla HTML files to GitHub Pages? Or should I wait for this issue to be fixed (or customize the workflow myself)?

**Comment by sidvishnoi** [comment]
Currently not supported, but I'll try to find some time for it soon. Meanwhile, it the files aren't changing often, you can manually push them to gh-pages; spec-prod won't delete them.
