### ISSUE TITLE
bikeshed echidna failure

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/spec-prod#50]
A bikeshed document which was successfully [published on Monday](https://lists.w3.org/Archives/Public/public-tr-notifications/2021Mar/0208.html) failed today: https://lists.w3.org/Archives/Public/public-tr-notifications/2021Apr/0003.html. I think it's trying to publish the `.bs` file instead of the generate `.html` one:
```
   $ mv ../mediacapture-image/index.bs Overview.html
  $ tar cvf /tmp/echidna.tar *
    Overview.html
    index.bs
  $ mv Overview.html ../mediacapture-image/index.bs
  $ curl 'https://labs.w3.org/echidna/api/request' -F "tar=@/tmp/echidna.tar" -F "token=***" -F "decision=https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html" -F "cc=dom@w3.org"
```

**Comment by sidvishnoi** [comment]
Released in v2.3.1.

**Comment by dontcallmedom** [comment]
I re-ran the action, and it failed with:
```
$ mv ../mediacapture-image/index.html Overview.html
  Failed
```

**Comment by dontcallmedom** [comment]
(I should clarify that it failed in the echidna part - the gh-pages publication worked https://github.com/w3c/mediacapture-image/runs/2252836549?check_suite_focus=true#step:3:157)
