### ISSUE TITLE
Consider allowing use of Bikeshed service instead of command-line

### ISSUE THREAD

**Issue by tidoust** [w3c/spec-prod#59]
The action installs and runs Bikeshed locally, which seems like a good approach. That said, updates to the source of Bikeshed are only reflected in the Python package when a new release is made, which may only happen after some time.

The [Bikeshed service](https://tabatkins.github.io/bikeshed/#remote) is always up-to-date with the contents of the default branch. Being able to use the service instead of the local install would make it possible to reflect Bikeshed changes (typically [boilerplate text](https://github.com/tabatkins/bikeshed/tree/main/bikeshed/boilerplate) updates) sooner rather than later in the specs.

Probably not high priority, and possibly an idea that could be dismissed entirely: changes should eventually find their way into the released package.

**Comment by sidvishnoi** [comment]
Maybe we can support `TOOLCHAIN: toolchain@version`. Then we can have `bikeshed@source` to install from GitHub repo directly.

BTW, does Bikeshed service allow uploading zip files (for includes)?

**Comment by tidoust** [comment]
> BTW, does Bikeshed service allow uploading zip files (for includes)?

I don't think so. [Example 2 in the documentation](https://tabatkins.github.io/bikeshed/#example-4c74cd22) on using an online URL has this note:

"If you are using additional files beyond your plain source file—local boilerplate files, sub-document includes, custom definition files, etc—this is the only way to make those still work via the curl API; Bikeshed will look for the additional files relative to the source document’s url."

**Comment by sidvishnoi** [comment]
Tracking this in https://github.com/w3c/spec-prod/issues/90 now
