### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/spec-prod#60]
It's a bit confusing have spec-prod as our editor's community list and as a repo... maybe we can rename this "auto-publish" or something more indicative of what the service does?

**Comment by marcoscaceres** [comment]
Any objection to changing the repo name to auto-publish?

**Comment by sidvishnoi** [comment]
Renaming might require all users to update their workflows. [76 instances](https://github.com/search?l=YAML&q=spec-prod&type=Code) if I trust GitHub search.

I kinda liked `spec-prod`. `auto-publish` is boring 😛

**Comment by marcoscaceres** [comment]
argh, ok, yeah... might have to let this go.
