### ISSUE TITLE
Docs should make it clear how to get an ECHIDNA_TOKEN

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/spec-prod#61]
The docs currently don't describe what is an ECHIDNA_TOKEN or how to get one.

**Comment by sidvishnoi** [comment]
https://github.com/w3c/spec-prod/blob/main/docs/options.md#w3c_echidna_token ?

**Comment by marcoscaceres** [comment]
Yes, but needs to be linked from the README.

**Comment by marcoscaceres** [comment]
Maybe the docs/ should just be folded into the README, tbh... having a docs/ folder means having to hunt for stuff in multiple places.

**Comment by marcoscaceres** [comment]
this is now fixed 🥳
