### ISSUE TITLE
Docs - unclear that you need to create the .yml files

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/spec-prod#68]
Was talking to @plehegar who mentioned that he hadn't realized that the comment at the top of the examples is the file that need to be created. 

We should have clear steps for creating the .yml file first. 

Also, we would like to "standardize" the file name (related #64) - so we can quickly/easily check across the entire W3C org which specs are not on autopublish.

**Comment by sidvishnoi** [comment]
Fixed by https://github.com/w3c/spec-prod/pull/69
