### ISSUE TITLE
Rename repo, suggest common workflow file name

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/spec-prod#72]
- ~Rename repo to `auto-publish` and replace all instances of spec-prod in docs. (https://github.com/w3c/spec-prod/issues/60 comes back, as automatic redirects after rename won't break workflows)~ Cancelled.
- [x] Send PRs to W3C repos to use `auto-publish.yml` as workflow name ([search](https://github.com/search?l=YAML&q=org%3Aw3c+spec-prod&type=Code)). ~Also rename repo there to avoid confusion/redirects.~

**Comment by sidvishnoi** [comment]
cc: @plehegar

**Comment by sidvishnoi** [comment]
Current status on workflow file names in org:W3C:
```
21	pr-push.yml
16	auto-publish.yml
9	build-validate-publish.yml
9	ci.yml
1	action.yml
```

**Comment by sidvishnoi** [comment]
Not renaming repo as the name is used quite often now, and is kinda a _brand_. Marcos has sent the PRs.
Will add a note "not to be confused with spec-prod mailing list".

**Comment by Bray40** [comment]
Nh
