### ISSUE TITLE
Specberus Errors

### ISSUE THREAD

**Issue by xfq** [w3c/spec-prod#83]
I don't know where the problem is (Bikeshed, Specberus, Echidna, the spec, or the config?), so I'll write it here first.

When configuring "auto-publish" (to `gh-pages` and to /TR) for https://github.com/w3c/sensors , I ran into this problem:

```
    📡 Request: https://labs.w3.org/echidna/api/status?id=6b7f496c-80bf-4949-a21f-4050c8681e0a
  
  Specberus Errors:
    No stability warning paragraph.
      {
        name: 'sotd.stability',
        section: 'document-status',
        rule: 'stability'
      }
    Cannot find the paragraph introducing document type and publisher in Status of This Document.
      { name: 'sotd.publish', section: 'document-status', rule: 'publish' }
    The document must mention the governing process: 15 September 2020
      { name: 'sotd.process-document' }
    No <em>&ldquo;status of this document&rdquo;</em> introduction (eg absent, not using HTTPS, wrong copy).
      {
        name: 'sotd.supersedable',
        section: 'document-status',
        rule: 'boilerplateTRDoc'
      }
    No <em>&ldquo;status of this document&rdquo;</em> introduction link to TR (or perhaps not using HTTPS).
      {
        name: 'sotd.supersedable',
        section: 'document-status',
        rule: 'boilerplateTRDoc'
      }
    Unable to find the deliverer
      {
        name: 'sotd.group-homepage',
        section: 'document-status',
        rule: 'WGLink'
      }
    Required patent policy paragraph not found. Expected text related to patent policy requirements: <blockquote>^This document was produced by a group operating under the( 15 September 2020| 1 August 2017)? W3C Patent Policy. ?W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy.$</blockquote>
      { name: 'sotd.pp' }
    Retrieved "previous" and "latest" documents, but their contents don't match.
      { name: 'headers.dl', section: 'front-matter', rule: 'docIDFormat' }
  
  Details: https://labs.w3.org/echidna/api/status?id=6b7f496c-80bf-4949-a21f-4050c8681e0a
  💥 Echidna publish has failed.
```

I tried to generate a CRD using Bikeshed locally, but the [stability warning paragraph](https://github.com/w3c/specberus/blob/2d79e706121ef49138927f9212a52ca7522568f2/lib/rules/sotd/stability.js#L11) was there.

The job was run in https://github.com/w3c/sensors/runs/2783645525 and the config file is here: https://github.com/w3c/sensors/blob/main/.github/workflows/auto-publish.yml

**Comment by sidvishnoi** [comment]
I don't think it's from the action. Questions:
- Does CRD require some additional metadata in Bikeshed?
- Did you run the same command locally as shown in the logs?

To confirm, I'll make following changes to the action:
- add some additional debug logs, like printing python/bikeshed versions (https://github.com/w3c/spec-prod/issues/85)
- upload built document as an artifact so it can be diagnosed later (https://github.com/w3c/spec-prod/issues/84)
- and hopefully make some time for https://github.com/w3c/spec-prod/issues/3

**Comment by xfq** [comment]
> * Does CRD require some additional metadata in Bikeshed?

I don't think so.

> * Did you run the same command locally as shown in the logs?

Yes. I ran `bikeshed --die-on=fatal spec "index.bs" "index.bs.built.html"` locally.

Is it possible that the Bikeshed in spec-prod is not the latest version? I sent a PR to Bikeshed recently: https://github.com/tabatkins/bikeshed/pull/2078

> * Does it make sense to pass a CR as "previous version" to CRD? (I'm yet to fully integrate the W3C publish process in the action)
>   `--md-previous-version="https://www.w3.org/TR/2019/CR-generic-sensor-20191212/"`

Do you mean in `auto-publish.yml`? If so, I may need to update this file frequently, which is cumbersome.

-----

> To confirm, I'll make following changes to the action:
> 
> * add some additional debug logs, like printing python/bikeshed versions (#85)
> * upload built document as an artifact so it can be diagnosed later (#84)
> * and hopefully make some time for #3

Thank you!

**Comment by deniak** [comment]
I looked at the document generated by spec-prod (attached [Generic Sensor API.zip](https://github.com/w3c/spec-prod/files/6637083/Generic.Sensor.API.zip)) and the SOTD is missing all the required paragraphs.

After updating bikeshed, I tried to generate the snapshot locally using @sidvishnoi's command but it doesn't seem to take https://github.com/tabatkins/bikeshed/blob/main/bikeshed/boilerplate/dap/status-CRD.include and I'm also missing the paragraphs.

I suspect something's missing with how bikeshed handles CRD but I don't explain how @xfq is able to generate the right snapshot.

**Comment by deniak** [comment]
Do you know if bikeshed needs to be re-published to PyPI? spec-prod installs bikeshed using `pip` which doesn't include the latest commits: https://pypi.org/project/bikeshed/

**Comment by xfq** [comment]
I guess the possible reason for this issue is that I have been using the bleeding-edge tip-of-tree version of Bikeshed, but the [latest released version](https://github.com/tabatkins/bikeshed/blob/main/bikeshed/spec-data/readonly/bikeshed-version.txt) does not include my recent commit.

I will ask if Tab can release a new version.

**Comment by xfq** [comment]
Bikeshed [released](https://github.com/tabatkins/bikeshed/commit/66a3ea0eb27d0500e3cb59e7fddd845a4719bb83) a new version. I tried re-running the job and it still seems to have the same problem.

**Comment by xfq** [comment]
Filed https://github.com/tabatkins/bikeshed/pull/2086

**Comment by deniak** [comment]
This time, I don't think it's the same issue. I'm attaching the snapshot sent to Echidna ([Generic Sensor API.zip](https://github.com/w3c/spec-prod/files/6662013/Generic.Sensor.API.zip)).
Now, the only problem is the stability paragraph. Pubrules expects:
```
Publication as a Candidate Recommendation does not imply endorsement by the W3C Membership. A Candidate Recommendation Draft integrates changes from the previous Candidate Recommendation that the Working Group intends to include in a subsequent Candidate Recommendation Snapshot.
```
instead of
```
Publication as a Candidate Recommendation Draft does not imply endorsement by the W3C Membership. This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress. 
```

**Comment by xfq** [comment]
Thanks, @deniak! Since this is a Bikeshed issue, I will close this issue and fix it in Bikeshed.
