### ISSUE TITLE
Use bikeshed version from github rather than pip

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/spec-prod#90]
Since the releases from bikeshed to pip aren't automated, there can be a gap between fixes brought to boilerplate files landed on github, and their availability through spec-prod (which uses the pip version of bikeshed).

To avoid that delay and reduce the confusion it creates (as e.g. in #83 and more recently for myself with webnn), I think it would be best if spec-prod were to use the latest version of bikeshed from github rather than pip.

**Comment by sidvishnoi** [comment]
See https://github.com/w3c/spec-prod/issues/59#issuecomment-839531265

**Comment by jyasskin** [comment]
@tabatkins probably has opinions here. I believe the pip releases are helpful in increasing stability.

**Comment by tabatkins** [comment]
What I really need to do is decouple the boilerplates from the code updates, so they can be received by a `bikeshed update` and I don't have to push new pip versions for them. It's on my plate of things to do near-term.

So I recommend just sticking with pip for code stability, and waiting for me to do this decoupling.

**Comment by dontcallmedom** [comment]
with [bikeshed 3.1 available on pip](https://pypi.org/project/bikeshed/#history) and featuring autonomous boilerplate, I think this issue can be closed as overtaken by events.
