### ISSUE TITLE
Wrong SOURCE path normalization when no filename and depth > 1

### ISSUE THREAD

**Issue by tidoust** [w3c/spec-prod#92]
The action fails when `SOURCE` is a relative path at a depth greater than 1 that does not include the filename.

This happens because the code in `getNormalizedPath` has specific logic to handle the case when the path does not include the filename:
https://github.com/w3c/spec-prod/blob/70df2970129eee554f7051cb1620031276c2dd0a/src/prepare-build.ts#L91

... but that logic fails to account for the general case where there may be some information to preserve in `parsed.dir`. The line should rather be:

```js
parsed.dir = path.join(parsed.dir, parsed.base);
```

Note the bug does not happen if `SOURCE` includes the filename (e.g. `level1/level2/index.html` works fine), simply because that logic then does not run.

Via https://github.com/w3c/epub-specs/pull/1764/checks?check_run_id=3242185472

**Comment by sidvishnoi** [comment]
Closed via https://github.com/w3c/spec-prod/pull/93
