### ISSUE TITLE
spec-prod started failing the ipr check on our wicg sanitizer-api repo

### ISSUE THREAD

**Issue by mozfreddyb** [w3c/spec-prod#96]
There's an HTTP 500 error on the ipr check in https://github.com/WICG/sanitizer-api/pull/97 and we have changed nothing.
Is this an issue with the spec-prod action?

**Comment by sidvishnoi** [comment]
spec-prod has no relation to the IPR check bot. It could be a temporary error in IPR check server, or it might require a manual approval using the admin UI.

**Comment by sidvishnoi** [comment]
@deniak might be able to tell details of IPR check bot
